### ISSUE TITLE
Remove non-session related keybindings

### ISSUE THREAD

**Issue by axelson** [siadat/session-finder#1]
Hi, I am enjoying your session-finder plugin! However, some of the keybindings are clobbering my existing keybindings and I don't feel that bindings like: `bind-key -n 'M-l' select-window -t +1` belong in a "session-finder" plugin. Is it possible for those to be removed or made optional?

**Comment by siadat** [comment]
Thank you for raising this issue! Sure, remove them and send a pull request if you feel like it. Otherwise, I will do it myself:)

**Comment by axelson** [comment]
Thanks! Submitted as PR #2
