### ISSUE TITLE
session-finder does not find sessions with spaces

### ISSUE THREAD

**Issue by axelson** [siadat/session-finder#3]
Session finder currently does not find sessions that have spaces in the name such as "my work" or "my first project". It would be nice if it did find them.

**Comment by siadat** [comment]
You are right. Would you be able to send a PR?

**Comment by axelson** [comment]
Yeah I would be willing to. Just need to find the time. Should be relatively straightforward though.

**Comment by siadat** [comment]
Would be nice! Thanks :)

**Comment by axelson** [comment]
I'm completely unable to reproduce this now so I'm going to close this issue.

**Comment by axelson** [comment]
Thanks, I realized over the weekend that the issue wasn't with finding the sessions, but with switching to them. But your patch https://github.com/siadat/session-finder/commit/f40b115d3d1553da9a44373814a6c6d52cd5f57b fixes it! 🎊

**Comment by siadat** [comment]
Awesome! 👌
