### ISSUE TITLE
session-finder does not find sessions that are attached

### ISSUE THREAD

**Issue by axelson** [siadat/session-finder#4]
I'm not sure if this is everyone's preference but I'd prefer for session-finder to find *all* tmux sessions, including those that are attached already.

**Comment by siadat** [comment]
Thanks for opening this issue. Could you explain what specific use case was in your mind?

My assumption was that session-finder is used when we want to switch to a different session. In which case, the user doesn't need to see the current session. Maybe we could show the user the current session in some other way though.

**Comment by axelson** [comment]
My specific use case is that I have two computers, a desktop and a laptop. Unfortunately when I use my laptop it physically blocks access to the keyboard of the desktop. So to control the desktop I SSH from my laptop to the desktop. So when I use tmux from the SSH I want to be able to connect to the tmux session that is already displayed on the desktop. So this is a different use case then showing the current session, I am fine not showing the current session, I just want to show all other tmux sessions, including those that are already attached.

**Comment by siadat** [comment]
If you SSH into your laptop, and attach to tmux (eg with `tmux -2 attach -d`) does it re-open the session that was open on your laptop? Is this your desired behavior?

**Comment by axelson** [comment]
If I run a command like `tmux -2 attach -d -t viz` (where "viz" is the name of the currently attached session) then I am able to connect to that session. However the behavior that I would expect would be to not include `-d` so that now the same session is open on both computers. This is because I use session-finder as a fast and easy way to switch between my many tmux sessions (I'll often have 5 or 6 open).

**Comment by siadat** [comment]
Could you pull the new changes and see if it resolves your issue? Thanks!

**Comment by axelson** [comment]
Thanks that works for me! (although I created #6 as a fix to the hard-coded fzf path)
